=== ALLOcloud/OpenAPT/meta-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "required": [
    "repositories",
    "mirrors",
    "snapshots",
    "publishings"
  ],
  "properties": {
    "repositories": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^.+$": {
          "type": "object",
          "properties": {
            "architectures": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "component": {
              "type": "string"
            },
            "distribution": {
              "type": "string"
            },
            "comment": {
              "type": "string"
            }
          }
        }
      }
    },
    "mirrors": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^.+$": {
          "type": "object",
          "properties": {
            "archive": {
              "type": "string"
            },
            "distribution": {
              "type": "string"
            },
            "components": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "architectures": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "filter": {
              "type": "string"
            },
            "filterWithDeps": {
              "type": "boolean"
            },
            "withSources": {
              "type": "boolean"
            },
            "withUdebs": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "publishings": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^.+$": {
          "oneOf": [
            {
              "type": "object",
              "required": [
                "snapshot"
              ],
              "properties": {
                "snapshot": {
                  "type": "string",
                  "pattern": "^.+$"
                }
              }
            }, {
              "type": "object",
              "required": [
                "repository"
              ],
              "properties": {
                "repository": {
                  "type": "string",
                  "pattern": "^.+$"
                }
              }
            }
          ]
        }
      }
    },
    "snapshots": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^.+$": {
          "oneOf": [
            {
              "type": "object",
              "required": [
                "type",
                "repository"
              ],
              "properties": {
                "type": {
                  "const": "create"
                },
                "repository": {
                  "type": "string",
                  "pattern": "^.+$"
                },
                "architectures": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }, {
              "type": "object",
              "required": [
                "type",
                "mirror"
              ],
              "properties": {
                "type": {
                  "const": "create"
                },
                "mirror": {
                  "type": "string",
                  "pattern": "^.+$"
                },
                "architectures": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }, {
              "type": "object",
              "required": [
                "type",
                "sources"
              ],
              "properties": {
                "type": {
                  "const": "merge"
                },
                "sources": {
                  "type": "array",
                  "minItems": 2,
                  "items": {
                    "type": "string",
                    "pattern": "^.+$"
                  }
                },
                "architectures": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "latest": {
                  "type": "boolean"
                },
                "noRemove": {
                  "type": "boolean"
                }
              }
            }, {
              "type": "object",
              "required": [
                "type",
                "source",
                "filter"
              ],
              "properties": {
                "type": {
                  "const": "filter"
                },
                "source": {
                  "type": "string",
                  "pattern": "^.+$"
                },
                "filter": {
                  "type": "string"
                },
                "withDeps": {
                  "type": "boolean"
                },
                "architectures": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          ]
        }
      }
    }
  }
}

=== ALLOcloud/OpenAPT/tests/e2e/cases/2_allocloud_complex/input.json
{
  "repositories": {
    "allocloud": {}
  },
  "mirrors": {
    "debian_buster": {
      "archive": "http://deb.debian.org/debian",
      "distribution": "buster",
      "filter": "python3-psycopg2 | python3-aiopg"
    },
    "debian_bullseye": {
      "archive": "http://deb.debian.org/debian",
      "distribution": "bullseye",
      "filter": "python3-psycopg2"
    },
    "aptly": {
      "archive": "http://repo.aptly.info/",
      "distribution": "squeeze"
    }
  },
  "snapshots": {
    "allocloud": {
      "type": "create",
      "repository": "allocloud"
    },
    "debian_buster": {
      "type": "create",
      "mirror": "debian_buster"
    },
    "debian_bullseye": {
      "type": "create",
      "mirror": "debian_bullseye"
    },
    "aptly": {
      "type": "create",
      "mirror": "aptly"
    },
    "allocloud_buster": {
      "type": "merge",
      "sources": [
        "debian_buster",
        "allocloud"
      ],
      "latest": true
    },
    "allocloud_apt_aptly": {
      "type": "pull",
      "source": "aptly",
      "recipient": "allocloud_buster",
      "packageQueries": [
        "aptly"
      ]
    },
    "allocloud_buster_numberland_bullseye": {
      "type": "pull",
      "source": "debian_bullseye",
      "recipient": "allocloud_buster",
      "packageQueries": [
        "python3-psycopg2"
      ]
    },
    "allocloud_apt": {
      "type": "filter",
      "source": "allocloud_apt_aptly",
      "filter": "openapt | aptly",
      "withDeps": true
    },
    "allocloud_numberland": {
      "type": "filter",
      "source": "allocloud_buster_numberland_bullseye",
      "filter": "Name (% allocloud-numberland*)",
      "withDeps": true
    },
    "allocloud_yankee": {
      "type": "filter",
      "source": "allocloud_buster",
      "filter": "Name (% allocloud-yankee*)",
      "withDeps": true
    }
  },
  "publishings": {
    "allocloud/apt": {
      "snapshot": "allocloud_apt",
      "distribution": "buster"
    },
    "allocloud/numberland": {
      "snapshot": "allocloud_numberland",
      "distribution": "buster"
    },
    "allocloud-yankee": {
      "snapshot": "allocloud_yankee",
      "distribution": "buster"
    }
  }
}

=== ALLOcloud/OpenAPT/tests/e2e/cases/1_allocloud_buster/input.json
{
  "repositories": {
    "allocloud": {
    }
  },
  "mirrors": {
    "debian_buster": {
      "archive": "http://deb.debian.org/debian",
      "distribution": "buster",
      "filter": "python3-psycopg2 | python3-aiopg"
    },
    "debian_bullseye": {
      "archive": "http://deb.debian.org/debian",
      "distribution": "bullseye",
      "filter": "python3-psycopg2"
    }
  },
  "snapshots": {
    "debian_buster": {
      "type": "create",
      "mirror": "debian_buster"
    },
    "debian_bullseye": {
      "type": "create",
      "mirror": "debian_bullseye"
    },
    "allocloud": {
      "type": "create",
      "repository": "allocloud"
    },
    "allocloud_buster": {
      "type": "merge",
      "sources": [
        "debian_buster",
        "allocloud"
      ]
    },
    "allocloud_buster_pulls": {
      "type": "pull",
      "source": "debian_bullseye",
      "recipient": "allocloud_buster",
      "packageQueries": [
        "python3-psycopg2"
      ]
    }
  },
  "publishings": {
    "allocloud-buster": {
      "distribution": "buster",
      "snapshot": "allocloud_buster_pulls"
    }
  }
}

=== ALLOcloud/OpenAPT/example.json
{
  "repositories": {
    "allocloud": {
    }
  },
  "mirrors": {
    "debian_buster": {
      "archive": "http://ftp.belnet.be/debian",
      "distribution": "buster",
      "filter": "postgresql-server"
    }
  },
  "snapshots": {
    "allocloud": {
      "type": "create",
      "repository": "allocloud"
    },
    "buster": {
      "type": "create",
      "mirror": "debian_buster"
    },
    "numberland": {
      "type": "merge",
      "sources": [
        "allocloud_filtered",
        "buster"
      ]
    },
    "allocloud_filtered": {
      "type": "filter",
      "source": "allocloud",
      "filter": ""
    }
  },
  "publishings": {
    "numberland": {
      "snapshot": "numberland"
    }
  }
}
