=== ALLOcloud/OpenAPT/allocloud/openapt/specs/openapt-specs_1.0.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$id": "https://gitlab.eyepea.eu/allocloud/open-apt/raw/develop/meta-schema.json",
  "definitions": {
    "architecture": {
      "type": "string"
    },
    "architectures": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/architecture"
      }
    },
    "component": {
      "type": "string"
    },
    "components": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/component"
      }
    },
    "filter": {
      "oneOf": [
        {
          "type": "string"
        }, {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ]
    }
  },
  "type": "object",
  "required": [
    "openapt",
    "repositories",
    "mirrors",
    "snapshots",
    "publishings"
  ],
  "properties": {
    "openapt": {
      "type": "string"
    },
    "repositories": {
      "type": "object",
      "additionalProperties": [
        {
          "type": "null"
        }, {
          "type": "object",
          "properties": {
            "architectures": {
              "$ref": "#/definitions/architectures"
            },
            "component": {
              "$ref": "#/definitions/component"
            },
            "distribution": {
              "type": "string"
            },
            "comment": {
              "type": "string"
            }
          }
        }
      ]
    },
    "mirrors": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "required": [
          "archive",
          "distribution"
        ],
        "properties": {
          "archive": {
            "type": "string"
          },
          "distribution": {
            "type": "string"
          },
          "components": {
            "$ref": "#/definitions/components"
          },
          "architectures": {
            "$ref": "#/definitions/architectures"
          },
          "filter": {
            "$ref": "#/definitions/filter"
          },
          "filterWithDeps": {
            "type": "boolean"
          },
          "withSources": {
            "type": "boolean"
          },
          "withUdebs": {
            "type": "boolean"
          }
        }
      }
    },
    "publishings": {
      "type": "object",
      "additionalProperties": {
        "oneOf": [
          {
            "type": "object",
            "required": [
              "snapshot",
              "distribution"
            ],
            "properties": {
              "snapshot": {
                "type": "string"
              },
              "distribution": {
                "type": "string"
              },
              "prefix": {
                "type": "string"
              },
              "components": {
                "$ref": "#/definitions/components"
              }
            }
          }, {
            "type": "object",
            "required": [
              "repository"
            ],
            "properties": {
              "repository": {
                "type": "string"
              },
              "components": {
                "$ref": "#/definitions/components"
              }
            }
          }
        ]
      }
    },
    "snapshots": {
      "type": "object",
      "additionalProperties": {
        "anyOf": [
          {
            "type": "object",
            "required": [
              "type",
              "repository"
            ],
            "properties": {
              "type": {
                "const": "create"
              },
              "repository": {
                "type": "string"
              },
              "architectures": {
                "$ref": "#/definitions/architectures"
              }
            }
          }, {
            "type": "object",
            "required": [
              "type",
              "mirror"
            ],
            "properties": {
              "type": {
                "const": "create"
              },
              "mirror": {
                "type": "string"
              },
              "architectures": {
                "$ref": "#/definitions/architectures"
              }
            }
          }, {
            "type": "object",
            "required": [
              "type",
              "sources"
            ],
            "properties": {
              "type": {
                "const": "merge"
              },
              "sources": {
                "type": "array",
                "minItems": 2,
                "items": {
                  "type": "string"
                }
              },
              "architectures": {
                "$ref": "#/definitions/architectures"
              },
              "latest": {
                "type": "boolean"
              },
              "noRemove": {
                "type": "boolean"
              }
            }
          }, {
            "type": "object",
            "required": [
              "type",
              "source",
              "filter"
            ],
            "properties": {
              "type": {
                "const": "filter"
              },
              "source": {
                "type": "string"
              },
              "filter": {
                "$ref": "#/definitions/filter"
              },
              "withDeps": {
                "type": "boolean"
              },
              "architectures": {
                "$ref": "#/definitions/architectures"
              }
            }
          }, {
            "type": "object",
            "required": [
              "type",
              "source",
              "recipient",
              "filter"
            ],
            "properties": {
              "type": {
                "const": "pull"
              },
              "source": {
                "type": "string"
              },
              "recipient": {
                "type": "string"
              },
              "filter": {
                "$ref": "#/definitions/filter"
              },
              "allMatches": {
                "type": "boolean"
              },
              "noRemove": {
                "type": "boolean"
              }
            }
          }
        ]
      }
    }
  }
}

=== ALLOcloud/OpenAPT/tests/e2e/cases/example_preexisting_mirror/schema.json
{
  "openapt": "1.0",
  "repositories": {
  },
  "mirrors": {
    "debian_stretch": {
      "archive": "http://deb.debian.org/debian",
      "distribution": "stretch",
      "filter": "toilet"
    },
    "debian_buster": {
      "archive": "http://deb.debian.org/debian",
      "distribution": "buster",
      "filter": "toilet"
    }
  },
  "snapshots": {
    "debian_stretch": {
      "type": "create",
      "mirror": "debian_stretch"
    },
    "debian_buster": {
      "type": "create",
      "mirror": "debian_buster"
    }
  },
  "publishings": {
  }
}

=== ALLOcloud/OpenAPT/tests/e2e/cases/example_preexisting_mirror_filter_changed/schema.json
{
  "openapt": "1.0",
  "repositories": {
  },
  "mirrors": {
    "debian_buster": {
      "archive": "http://deb.debian.org/debian",
      "distribution": "buster",
      "filter": "toilet"
    }
  },
  "snapshots": {
    "debian_buster": {
      "type": "create",
      "mirror": "debian_buster"
    }
  },
  "publishings": {
  }
}

=== ALLOcloud/OpenAPT/tests/e2e/cases/example_limited/schema.json
{
  "openapt": "1.0",
  "repositories": {
    "allocloud": {
    }
  },
  "mirrors": {
    "debian_buster": {
      "archive": "http://deb.debian.org/debian",
      "distribution": "buster",
      "filter": "toilet"
    }
  },
  "snapshots": {
    "allocloud": {
      "type": "create",
      "repository": "allocloud"
    },
    "buster": {
      "type": "create",
      "mirror": "debian_buster"
    },
    "openapt": {
      "type": "merge",
      "sources": [
        "allocloud_filtered",
        "buster"
      ]
    },
    "allocloud_filtered": {
      "type": "filter",
      "source": "allocloud",
      "filter": "toilet",
      "withDeps": true
    }
  },
  "publishings": {
    "openapt": {
      "snapshot": "openapt",
      "distribution": "prod",
      "prefix": "repositories/openapt"
    }
  }
}

=== ALLOcloud/OpenAPT/tests/e2e/cases/allocloud_complex/schema.json
{
  "openapt": "1.0",
  "repositories": {
    "allocloud": {}
  },
  "mirrors": {
    "debian_buster": {
      "archive": "http://deb.debian.org/debian",
      "distribution": "buster",
      "filter": "python3-psycopg2 | python3-aiopg"
    },
    "debian_bullseye": {
      "archive": "http://deb.debian.org/debian",
      "distribution": "bullseye",
      "filter": "python3-psycopg2"
    },
    "aptly": {
      "archive": "http://repo.aptly.info/",
      "distribution": "squeeze"
    }
  },
  "snapshots": {
    "allocloud": {
      "type": "create",
      "repository": "allocloud"
    },
    "debian_buster": {
      "type": "create",
      "mirror": "debian_buster"
    },
    "debian_bullseye": {
      "type": "create",
      "mirror": "debian_bullseye"
    },
    "aptly": {
      "type": "create",
      "mirror": "aptly"
    },
    "allocloud_buster": {
      "type": "merge",
      "sources": [
        "debian_buster",
        "allocloud"
      ],
      "latest": true
    },
    "allocloud_apt_aptly": {
      "type": "pull",
      "source": "aptly",
      "recipient": "allocloud_buster",
      "filter": [
        "aptly"
      ]
    },
    "allocloud_buster_numberland_bullseye": {
      "type": "pull",
      "source": "debian_bullseye",
      "recipient": "allocloud_buster",
      "filter": [
        "python3-psycopg2"
      ]
    },
    "allocloud_apt": {
      "type": "filter",
      "source": "allocloud_apt_aptly",
      "filter": "openapt | aptly",
      "withDeps": true
    },
    "allocloud_numberland": {
      "type": "filter",
      "source": "allocloud_buster_numberland_bullseye",
      "filter": "Name (% allocloud-numberland*)",
      "withDeps": true
    },
    "allocloud_yankee": {
      "type": "filter",
      "source": "allocloud_buster",
      "filter": "Name (% allocloud-yankee*)",
      "withDeps": true
    }
  },
  "publishings": {
    "apt": {
      "snapshot": "allocloud_apt",
      "distribution": "apt",
      "prefix": "allocloud"
    },
    "numberland": {
      "snapshot": "allocloud_numberland",
      "distribution": "prod",
      "prefix": "allocloud/numberland",
      "component": "test"
    },
    "yankee": {
      "snapshot": "allocloud_yankee",
      "distribution": "prod",
      "prefix": "allocloud/yankee"
    }
  }
}
